-- Insert properties (Kantstrasse, Hindenburgdamm, and Kottbusser Damm apartments)
INSERT INTO properties (
  slug,
  name,
  address,
  size,
  bedrooms,
  bathrooms,
  max_guests,
  base_price,
  cleaning_fee,
  pet_fee,
  weekly_discount,
  monthly_discount,
  min_stay,
  pet_friendly,
  amenities,
  images,
  coordinates,
  is_active
) VALUES
(
  'kantstrasse',
  'Kantstrasse Apartment',
  'Kantstrasse 99, 10627 Berlin',
  90,
  2,
  1,
  5,
  120.00,
  50.00,
  0,
  10,
  20,
  3,
  false,
  '["wifi", "workspace", "kitchen", "washer", "dryer", "tv", "ac", "heating", "dishwasher", "parking", "elevator"]'::jsonb,
  '[]'::jsonb,
  '{"lat": 52.5065, "lng": 13.3035}'::jsonb,
  true
),
(
  'hindenburgdamm',
  'Hindenburgdamm Apartment',
  'Hindenburgdamm 85, 12203 Berlin',
  75,
  2,
  1,
  4,
  95.00,
  40.00,
  20.00,
  10,
  20,
  3,
  true,
  '["wifi", "kitchen", "washer", "tv", "heating", "pet_friendly", "dishwasher", "balcony"]'::jsonb,
  '[]'::jsonb,
  '{"lat": 52.4369, "lng": 13.3160}'::jsonb,
  true
),
(
  'kottbusserdamm',
  'Kottbusser Damm Apartment',
  'Kottbusser Damm 68, 10967 Berlin',
  55,
  2,
  1,
  7,
  140.00,
  60.00,
  25.00,
  10,
  20,
  3,
  true,
  '["wifi", "pet_friendly", "kitchen", "washer", "dryer", "tv", "heating", "smoke_detector", "first_aid", "parking", "garden", "dishwasher", "ev_charger", "public_transport"]'::jsonb,
  '[]'::jsonb,
  '{"lat": 52.4922, "lng": 13.4197}'::jsonb,
  true
)
ON CONFLICT (slug) DO NOTHING;

-- Note: Images should be uploaded to storage and then URLs updated in the images JSONB field
-- This can be done through the admin dashboard or via API after setup
